version: '3'
services:
  webcaptioner-ng:
    image: webcaptioner-ng:latest
    restart: unless-stopped
    environment:
      - REACT_APP_WEBCAPTIONER_SERVER
      - REACT_APP_YOUTUBE_REGION
      - REACT_APP_SEND_TIMESTAMP
      - REACT_APP_SEND_TIMESTAMP_COUNT
      - REACT_APP_MAX_LINES_IN_HISTORY
      - REACT_APP_DEFAULT_VOSK_SAMPLE_RATE
      - REACT_APP_RECORDING_INFORMATION_LINE
      - REACT_APP_DEFAULT_AUDIO_FORMAT
  #    ports:
  #        - '80:3000'

  webcaptioner-vosk-server:
    image: vosk_server_whisper:latest
    privileged: true
    restart: unless-stopped
    environment:
      - VOSK_SAMPLE_RATE
      - VOSK_LOG_AUDIO
      - MODEL_PATH_FULL
      - VOSK_SHOW_WORDS
    volumes:
      - ./logs:/logs
      - ./whisper/:/whisper
#    ports:
#        - '80:4000'
